export const orderCatalog = {
    instagram: {
        id: 'instagram',
        name: 'Instagram',
        products: [
            {
                id: 'likes',
                name: 'Likes',
                linkLabel: 'Post URL',
                linkHint: 'Paste an Instagram post or reel URL',
                placeholder: 'https://www.instagram.com/p/...',
                min: 5,
                max: 1000000,
                packages: [
                    { amount: 50, price: 0.49 },
                    { amount: 100, price: 0.79 },
                    { amount: 250, price: 1.1 },
                    { amount: 500, price: 1.25 },
                    { amount: 1000, price: 1.4 },
                    { amount: 2500, price: 3.2 },
                    { amount: 5000, price: 5.9 },
                    { amount: 10000, price: 10.5 },
                ],
            },
            {
                id: 'followers',
                name: 'Followers',
                linkLabel: 'Profile URL',
                linkHint: 'Paste an Instagram profile URL',
                placeholder: 'https://www.instagram.com/username',
                min: 10,
                max: 500000,
                packages: [
                    { amount: 100, price: 1.99 },
                    { amount: 250, price: 3.9 },
                    { amount: 500, price: 6.5 },
                    { amount: 1000, price: 11.9 },
                    { amount: 2500, price: 26 },
                    { amount: 5000, price: 48 },
                ],
            },
            {
                id: 'views',
                name: 'Views',
                linkLabel: 'Reel / Video URL',
                linkHint: 'Paste an Instagram reel or video URL',
                placeholder: 'https://www.instagram.com/reel/...',
                min: 100,
                max: 5000000,
                packages: [
                    { amount: 1000, price: 0.99 },
                    { amount: 5000, price: 2.5 },
                    { amount: 10000, price: 4.2 },
                    { amount: 25000, price: 8.9 },
                    { amount: 50000, price: 15 },
                ],
            },
            {
                id: 'comments',
                name: 'Comments',
                linkLabel: 'Post URL',
                linkHint: 'Paste an Instagram post URL',
                placeholder: 'https://www.instagram.com/p/...',
                min: 5,
                max: 10000,
                packages: [
                    { amount: 10, price: 1.5 },
                    { amount: 25, price: 3.2 },
                    { amount: 50, price: 5.5 },
                    { amount: 100, price: 9.9 },
                ],
            },
        ],
    },
    tiktok: {
        id: 'tiktok',
        name: 'TikTok',
        products: [
            {
                id: 'likes',
                name: 'Likes',
                linkLabel: 'Video URL',
                linkHint: 'Paste a TikTok video URL',
                placeholder: 'https://www.tiktok.com/@user/video/...',
                min: 10,
                max: 1000000,
                packages: [
                    { amount: 100, price: 0.69 },
                    { amount: 500, price: 1.9 },
                    { amount: 1000, price: 2.9 },
                    { amount: 5000, price: 9.5 },
                ],
            },
            {
                id: 'views',
                name: 'Views',
                linkLabel: 'Video URL',
                linkHint: 'Paste a TikTok video URL',
                placeholder: 'https://www.tiktok.com/@user/video/...',
                min: 100,
                max: 10000000,
                packages: [
                    { amount: 1000, price: 1.2 },
                    { amount: 5000, price: 5 },
                    { amount: 10000, price: 8.5 },
                    { amount: 50000, price: 28 },
                ],
            },
            {
                id: 'followers',
                name: 'Followers',
                linkLabel: 'Profile URL',
                linkHint: 'Paste a TikTok profile URL',
                placeholder: 'https://www.tiktok.com/@username',
                min: 10,
                max: 500000,
                packages: [
                    { amount: 100, price: 2.5 },
                    { amount: 500, price: 9.9 },
                    { amount: 1000, price: 17 },
                    { amount: 2500, price: 38 },
                ],
            },
        ],
    },
    youtube: {
        id: 'youtube',
        name: 'YouTube',
        products: [
            {
                id: 'views',
                name: 'Views',
                linkLabel: 'Video URL',
                linkHint: 'Paste a YouTube video URL',
                placeholder: 'https://www.youtube.com/watch?v=...',
                min: 100,
                max: 5000000,
                packages: [
                    { amount: 1000, price: 3.5 },
                    { amount: 5000, price: 12 },
                    { amount: 10000, price: 22 },
                    { amount: 25000, price: 48 },
                ],
            },
            {
                id: 'likes',
                name: 'Likes',
                linkLabel: 'Video URL',
                linkHint: 'Paste a YouTube video URL',
                placeholder: 'https://www.youtube.com/watch?v=...',
                min: 10,
                max: 100000,
                packages: [
                    { amount: 50, price: 1.8 },
                    { amount: 100, price: 2.9 },
                    { amount: 500, price: 9.5 },
                    { amount: 1000, price: 16 },
                ],
            },
            {
                id: 'subscribers',
                name: 'Subscribers',
                linkLabel: 'Channel URL',
                linkHint: 'Paste a YouTube channel URL',
                placeholder: 'https://www.youtube.com/@channel',
                min: 10,
                max: 100000,
                packages: [
                    { amount: 50, price: 4.5 },
                    { amount: 100, price: 7.9 },
                    { amount: 500, price: 32 },
                    { amount: 1000, price: 58 },
                ],
            },
        ],
    },
    facebook: {
        id: 'facebook',
        name: 'Facebook',
        products: [
            {
                id: 'likes',
                name: 'Post Likes',
                linkLabel: 'Post URL',
                linkHint: 'Paste a Facebook post URL',
                placeholder: 'https://www.facebook.com/.../posts/...',
                min: 10,
                max: 500000,
                packages: [
                    { amount: 100, price: 1.5 },
                    { amount: 500, price: 4.9 },
                    { amount: 1000, price: 8.5 },
                    { amount: 5000, price: 32 },
                ],
            },
            {
                id: 'followers',
                name: 'Page Followers',
                linkLabel: 'Page URL',
                linkHint: 'Paste a Facebook page URL',
                placeholder: 'https://www.facebook.com/pagename',
                min: 10,
                max: 200000,
                packages: [
                    { amount: 100, price: 2.2 },
                    { amount: 500, price: 8.9 },
                    { amount: 1000, price: 15 },
                ],
            },
        ],
    },
    x: {
        id: 'x',
        name: 'X / Twitter',
        products: [
            {
                id: 'likes',
                name: 'Likes',
                linkLabel: 'Tweet URL',
                linkHint: 'Paste a tweet URL',
                placeholder: 'https://x.com/user/status/...',
                min: 10,
                max: 500000,
                packages: [
                    { amount: 50, price: 0.99 },
                    { amount: 100, price: 1.5 },
                    { amount: 500, price: 4.5 },
                    { amount: 1000, price: 7.9 },
                ],
            },
            {
                id: 'followers',
                name: 'Followers',
                linkLabel: 'Profile URL',
                linkHint: 'Paste an X profile URL',
                placeholder: 'https://x.com/username',
                min: 10,
                max: 200000,
                packages: [
                    { amount: 100, price: 2.9 },
                    { amount: 500, price: 11 },
                    { amount: 1000, price: 19 },
                ],
            },
        ],
    },
};

export const countries = ['Worldwide', 'United States', 'United Kingdom', 'France', 'Germany', 'Algeria', 'Brazil', 'India'];
export const qualities = [
    { id: 'standard', label: 'Standard', hint: 'Fast delivery' },
    { id: 'premium', label: 'Premium', hint: 'Higher retention · +15%' },
];
